# -*- coding: utf-8 -*-
"""Data Ops Assignment Krishnam Raja.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vd0H9NVLB0ZK4xPA1MJgHlwpEtUW5IX0
"""

import pandas as pd
import logging
import os
from datetime import datetime
import sys
import io
from google.colab import files

# Set up logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.StreamHandler(sys.stdout)
    ]
)
logger = logging.getLogger('data_pipeline')

import logging
import pandas as pd

# Reset logging configuration (in case Colab already initialized it)
for handler in logging.root.handlers[:]:
    logging.root.removeHandler(handler)

# Basic config to print INFO-level logs
logging.basicConfig(
    level=logging.INFO,
    format='%(levelname)s:%(name)s:%(message)s'
)

# Set up logger
logger = logging.getLogger(__name__)

class DataPipeline:
    def __init__(self, call_logs_path, agent_roster_path, disposition_summary_path, output_path=None):
        self.call_logs_path = call_logs_path
        self.agent_roster_path = agent_roster_path
        self.disposition_summary_path = disposition_summary_path
        self.output_path = output_path  # Set output_path attribute here

        if output_path is None:
            self.output_path = os.getcwd()
        else:
            self.output_path = output_path

        # Initialize dataframes
        self.call_logs_df = None
        self.agent_roster_df = None
        self.disposition_summary_df = None
        self.merged_df = None
        self.performance_summary_df = None

        logger.info("Data Pipeline initialized with file paths")

    def _generate_summary_message(self, report_df):
        """
        Generate a summary message based on the report data.
        """
        # Example summary: Counting the number of agents and summarizing key metrics
        num_agents = report_df['agent_id'].nunique()
        total_calls = report_df['total_calls'].sum()
        avg_connect_rate = report_df['connect_rate_pct'].mean()

        summary_message = (
            f"Agent Performance Report Summary:\n"
            f"Total number of agents: {num_agents}\n"
            f"Total number of calls: {total_calls}\n"
            f"Average connect rate: {avg_connect_rate:.2f}%"
        )

        # Log the summary message
        logger.info(summary_message)

        # You can also return the summary message if needed
        return summary_message

    def _validate_dataframe(self, df, df_name, required_columns):
        """
        Validates that the required columns exist in the dataframe, checks for any missing values and duplicate rows.
        """
        logger.info(f"Validating {df_name} dataframe")

        # Check if all required columns are present in the dataframe
        missing_columns = [col for col in required_columns if col not in df.columns]
        if missing_columns:
          logger.error(f"Missing columns in {df_name}: {missing_columns}")
          raise ValueError(f"Missing columns in {df_name}: {missing_columns}")

        # Check for missing values in the required columns
        for col in required_columns:
          if df[col].isnull().any():
            logger.warning(f"Missing values in column {col} in {df_name}")

        # Check for duplicate rows
        duplicate_count = df.duplicated().sum()
        if duplicate_count > 0:
          logger.warning(f"{df_name} dataframe contains {duplicate_count} duplicate rows")
        else:
          logger.info(f"{df_name} dataframe contains no duplicate rows")

        # Success message if no missing columns or duplicates
        if not missing_columns and duplicate_count == 0:
          logger.info(f"No missing columns or duplicate rows found in {df_name}")

        logger.info(f"{df_name} validation completed")

# Define the ingest_and_validate method after the class definition
def ingest_and_validate(self):
    """
    Read all three files into pandas dataframes and perform basic validations.
    """
    logger.info("Starting data ingestion and validation")

    # Read CSV files
    try:
        self.call_logs_df = pd.read_csv(self.call_logs_path)
        logger.info(f"Successfully read call logs: {self.call_logs_df.shape[0]} rows")
    except Exception as e:
        logger.exception("Error reading call logs")
        raise

    try:
        self.agent_roster_df = pd.read_csv(self.agent_roster_path)
        logger.info(f"Successfully read agent roster: {self.agent_roster_df.shape[0]} rows")
    except Exception as e:
        logger.exception("Error reading agent roster")
        raise

    try:
        self.disposition_summary_df = pd.read_csv(self.disposition_summary_path)
        logger.info(f"Successfully read disposition summary: {self.disposition_summary_df.shape[0]} rows")
    except Exception as e:
        logger.exception("Error reading disposition summary")
        raise

    # Perform validation using _validate_dataframe method
    try:
        logger.info("Validation section begins")

        # Validate each dataframe
        self._validate_dataframe(self.call_logs_df, 'call_logs', ['call_id', 'agent_id', 'org_id', 'call_date'])
        self._validate_dataframe(self.agent_roster_df, 'agent_roster', ['agent_id', 'org_id'])
        self._validate_dataframe(self.disposition_summary_df, 'disposition_summary', ['agent_id', 'org_id', 'call_date'])

        # Convert 'call_date' to datetime in both dataframes if they exist
        if 'call_date' in self.call_logs_df.columns:
            self.call_logs_df['call_date'] = pd.to_datetime(self.call_logs_df['call_date'])
            logger.info("Successfully converted call_date to datetime in call_logs")

        if 'call_date' in self.disposition_summary_df.columns:
            self.disposition_summary_df['call_date'] = pd.to_datetime(self.disposition_summary_df['call_date'])
            logger.info("Successfully converted call_date to datetime in disposition_summary")

    except Exception as e:
        logger.exception("Error during validation or datetime conversion")
        raise

    logger.info("Data ingestion and validation completed")
    print("Reached end of method")  # for visual confirmation in Colab

# Update the class with the new method
setattr(DataPipeline, "ingest_and_validate", ingest_and_validate)

ingestor = DataPipeline('call_logs.csv', 'agent_roster.csv', 'disposition_summary.csv', output_path=None)
ingestor.ingest_and_validate()

def merge_data(self):
        """
        Merge the datasets using agent_id, org_id, and call_date.
        """
        logger.info("Starting data merging")

        # Merge call_logs with agent_roster
        try:
            merged_df = pd.merge(
                self.call_logs_df,
                self.agent_roster_df,
                on=['agent_id', 'org_id'],
                how='left',
                suffixes=('', '_roster')
            )
            logger.info(f"Merged call_logs with agent_roster: {merged_df.shape[0]} rows")

            # Count missing agent roster data
            missing_roster = merged_df['users_first_name'].isnull().sum()
            if missing_roster > 0:
                logger.warning(f"Found {missing_roster} calls with missing agent roster data")
        except Exception as e:
            logger.error(f"Error merging call_logs with agent_roster: {e}")
            raise

        # Merge with disposition_summary
        try:
            self.merged_df = pd.merge(
                merged_df,
                self.disposition_summary_df,
                on=['agent_id', 'org_id', 'call_date'],
                how='outer',
                suffixes=('', '_disp')
            )
            logger.info(f"Merged with disposition_summary: {self.merged_df.shape[0]} rows")

            # Count calls without disposition
            calls_without_disp = self.merged_df[self.merged_df['call_id'].notnull() & self.merged_df['login_time'].isnull()].shape[0]
            if calls_without_disp > 0:
                logger.warning(f"Found {calls_without_disp} calls without disposition data")

            # Count dispositions without calls
            disp_without_calls = self.merged_df[self.merged_df['call_id'].isnull() & self.merged_df['login_time'].notnull()].shape[0]
            if disp_without_calls > 0:
                logger.warning(f"Found {disp_without_calls} dispositions without call data")
        except Exception as e:
            logger.error(f"Error merging with disposition_summary: {e}")
            raise

        logger.info("Data merging completed")
  # Attach it to the existing class
setattr(DataPipeline, "merge_data", merge_data)
ingestor.merge_data()
print(ingestor.merged_df.head())

ingestor.merge_data()

def engineer_features(self):
        """
        Generate features for agent performance analysis.
        """
        logger.info("Starting feature engineering")

        # Group by agent_id, org_id, and call_date
        try:
            # Filter out rows with null agent_id, org_id, or call_date
            valid_data = self.merged_df.dropna(subset=['agent_id', 'org_id', 'call_date'])

            # Create a presence indicator (1 if login_time exists, else 0)
            valid_data['presence'] = valid_data['login_time'].notnull().astype(int)

            # Process only rows with call data for call metrics
            call_data = valid_data.dropna(subset=['call_id'])

            # Create aggregations
            agg_data = call_data.groupby(['agent_id', 'org_id', 'call_date']).agg(
                total_calls=('call_id', 'count'),
                unique_loans=('installment_id', 'nunique'),
                completed_calls=('status', lambda x: (x == 'completed').sum()),
                total_duration=('duration', 'sum')
            ).reset_index()

            # Add presence from valid_data
            presence_data = valid_data.groupby(['agent_id', 'org_id', 'call_date'])['presence'].max().reset_index()

            # Merge agg_data with presence_data
            agg_data = pd.merge(
                agg_data,
                presence_data,
                on=['agent_id', 'org_id', 'call_date'],
                how='outer'
            )

            # Handle agents in presence_data but not in agg_data (agents with presence but no calls)
            agg_data['total_calls'] = agg_data['total_calls'].fillna(0)
            agg_data['unique_loans'] = agg_data['unique_loans'].fillna(0)
            agg_data['completed_calls'] = agg_data['completed_calls'].fillna(0)
            agg_data['total_duration'] = agg_data['total_duration'].fillna(0)

            # Calculate additional metrics
            agg_data['connect_rate'] = (agg_data['completed_calls'] / agg_data['total_calls']).fillna(0)
            # Avoid division by zero for avg_call_duration_min
            agg_data['avg_call_duration_min'] = agg_data.apply(
                lambda row: (row['total_duration'] / row['total_calls'] / 60) if row['total_calls'] > 0 else 0,
                axis=1
            )

            # Get agent names from roster
            agent_names = self.agent_roster_df[['agent_id', 'org_id', 'users_first_name', 'users_last_name']]

            # Merge with agent names
            self.performance_summary_df = pd.merge(
                agg_data,
                agent_names,
                on=['agent_id', 'org_id'],
                how='left'
            )

            # Create full name column
            self.performance_summary_df['agent_full_name'] = (
                self.performance_summary_df['users_first_name'] + ' ' +
                self.performance_summary_df['users_last_name']
            )

            # Format connect_rate as percentage
            self.performance_summary_df['connect_rate_pct'] = self.performance_summary_df['connect_rate'] * 100

            logger.info(f"Created performance summary with {self.performance_summary_df.shape[0]} rows")

        except Exception as e:
            logger.error(f"Error in feature engineering: {e}")
            raise

        logger.info("Feature engineering completed")

setattr(DataPipeline, "engineer_features", engineer_features)

ingestor.engineer_features()

ingestor.performance_summary_df

def generate_report(self):
        """
        Generate and save the agent performance report.
        """
        logger.info("Generating agent performance report")

        try:
            # Prepare the output dataframe
            output_columns = [
                'call_date', 'agent_id', 'org_id', 'agent_full_name',
                'total_calls', 'unique_loans', 'connect_rate_pct',
                'avg_call_duration_min', 'presence'
            ]

            output_df = self.performance_summary_df[output_columns].copy()

            # Format columns
            output_df['connect_rate_pct'] = output_df['connect_rate_pct'].round(2)
            output_df['avg_call_duration_min'] = output_df['avg_call_duration_min'].round(2)

            # Sort by connect_rate and total_calls
            output_df = output_df.sort_values(by=['connect_rate_pct', 'total_calls'], ascending=[False, False])

            # Save to CSV
            output_file = os.path.join(self.output_path, 'agent_performance_summary.csv')
            output_df.to_csv(output_file, index=False)
            logger.info(f"Saved performance summary to {output_file}")

            # Generate a summary message
            self._generate_summary_message(output_df)

            # For Colab, also download the output file
            try:
                from google.colab import files
                files.download(output_file)
                logger.info("File download initiated for Colab")
            except:
                logger.warning("Not running in Google Colab, file download not available")

        except Exception as e:
            logger.error(f"Error generating report: {e}")
            raise

        logger.info("Report generation completed")

        return output_df
setattr(DataPipeline, "generate_report", generate_report)

report_df = ingestor.generate_report()

def _generate_summary_message(self, output_df):
    """
    Generate a Slack-style summary message.

    Args:
        output_df (DataFrame): Performance summary dataframe
    """
    try:
        # Get the latest date
        latest_date = output_df['call_date'].max().strftime('%Y-%m-%d')

        # Get top performer
        top_performer = output_df.iloc[0]
        top_name = top_performer['agent_full_name']
        top_rate = top_performer['connect_rate_pct']

        # Get total active agents (with presence = 1)
        active_agents = output_df[output_df['presence'] == 1].shape[0]

        # Get average call duration
        avg_duration = output_df['avg_call_duration_min'].mean().round(1)

        # Format message
        message = f"""
Agent Summary for {latest_date}
Top Performer: {top_name} ({top_rate:.0f}% connect rate)
Total Active Agents: {active_agents}
Average Duration: {avg_duration} min
"""
        print(message)

        # Save message to file
        message_file = os.path.join(self.output_path, 'agent_summary_message.txt')
        with open(message_file, 'w') as f:
            f.write(message)
        logger.info(f"Saved summary message to {message_file}")

        # For Colab, also download the message file
        try:
            from google.colab import files
            files.download(message_file)
            logger.info("Message file download initiated for Colab")
        except:
            logger.warning("Not running in Google Colab, file download not available")

    except Exception as e:
        logger.error(f"Error generating summary message: {e}")
        raise

setattr(DataPipeline, "_generate_summary_message", _generate_summary_message)

ingestor.generate_report()

def main():
    """
    Main function to run in Colab.
    """
    print("DPDzero Data Operations Assignment")
    print("==================================")

    # Create and run the pipeline
    try:
        pipeline = DataPipeline(
            'call_logs.csv',
            'agent_roster.csv',
            'disposition_summary.csv'
        )

        pipeline.ingest_and_validate()
        pipeline.merge_data()
        pipeline.engineer_features()
        performance_df = pipeline.generate_report()

        # Display the first few rows of the performance summary
        print("\nAgent Performance Summary (Top 10):")
        display(performance_df.head(10))

        # Display the whole dataframe for reference
        print("\nFull Performance Data:")
        display(performance_df)

        print("\nData pipeline completed successfully!")
        print("Two files have been generated and downloaded:")
        print("1. agent_performance_summary.csv - The complete performance report")
        print("2. agent_summary_message.txt - The Slack-style summary message")

    except Exception as e:
        print(f"Pipeline failed: {str(e)}")
        raise

# Run the main function
if __name__ == "__main__":
    main()